###
GET http://localhost:8081/items

###
POST http://localhost:8080/item
Content-Type: application/json

{"name": "phone", "price": 10000}

###
POST http://localhost:8080/item
Content-Type: application/json

{"name": "cup", "price": 50}

###
POST http://localhost:8080/item
Content-Type: application/json

{"name": "pen", "price": 100}

###
GET http://localhost:8080/item/d54b0535-a900-43e6-b2e0-17f5f070b528

###
PUT http://localhost:8080/item
Content-Type: application/json

{"id": "fd9e0d1d-75cc-4838-a85f-603163234d4b", "price": 30000}

###
DELETE http://localhost:8080/item/01923598-500d-4dbf-81b9-cd44dc8c370e


###
DELETE http://localhost:8080/item/6049df57-3276-4571-b790-8e7c5d7d83f0

###
GET /cart/0bd3e6e1-7657-464a-8787-a47e23324ff7
Host: localhost:8080

###
PUT /cart/checkout/0bd3e6e1-7657-464a-8787-a47e23324ff7/2c7df8c2-069e-4931-a6c3-e6bb68b0c3b3
Host: localhost:8080


###
POST /cart
Host: localhost:8080
Content-Type: application/json

{
  "client": "Mark",
  "items": [
    {
      "itemId": "fd9e0d1d-75cc-4838-a85f-603163234d4b",
      "amount": 2
    }]
}