POST localhost:8071/create/1

###
POST localhost:8071/create/10001

###
POST localhost:8071/update/1/1000

###
POST localhost:8071/update/10001/1000

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 1,
  "destinationId": 10001,
  "value": 101,
  "categoryId": 1
}

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 2,
  "destinationId": 1,
  "value": 123,
  "categoryId": 1
}