###
POST localhost:8071/update/2/123

###
POST localhost:8071/update/3/123


###
POST localhost:8071/update/1/-12

###
POST localhost:8071/update/3/4564

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 2,
  "destinationId": 3,
  "value": 122,
  "categoryId": 1
}

###
POST localhost:8071/transfer
Content-Type: application/json

{
  "sourceId": 1,
  "destinationId": 2,
  "value": 124,
  "categoryId": 1
}